### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by nishchalraj** [Magisk-Modules-Repo/iYTBP-Vanced-black-Magisk-Repo#2]
Hi! I am very fond of Yoututbe (Ad)vanced and been using it since a long time but today, I encountered a crash. It's like: When someone (any celebrity) is live and if we try to super chat with him by donating some money, there's an option **Super Chat** and after clicking it we get a slider for _how much money we want to donate_ , after moving the slider to any level if we click the **BUY AND SEND** button, the app crashes suddenly.
I wasn't able to see the logs because of some issues with my system but you can definitly check the crash. It will be good if this gets solved.

**Comment by nishchalraj** [comment]
Now it says, **sorry cannot open this link** when I click on the **buy and send** button

**Comment by zanezam** [comment]
interesting, any chance of a log after that happened? and another thing, can u try to use stock yt app too just to exclude a possible problem in the app version itself? would be good to know.
